laundry/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    StringField,
    PasswordField,
    EmailField,
    TelField,
    SubmitField,
    SelectField,
    TextAreaField,
    DateField,
    IntegerField
)
from wtforms.validators import Email, InputRequired



class EditProfile(FlaskForm):
    name = StringField(label="Name", render_kw={
        'placeholder': 'Name'
    })
    email = EmailField(label="E-mail", render_kw={
        'placeholder': 'Email'
    }, validators=[Email()])
    phone = TelField(label="Mobile Phone", render_kw={
        'placeholder': 'Mobile Phone'
    })
    address = StringField(label="Default Address", render_kw={
        'placeholder': 'Default Address'
    })
    current_password = PasswordField(render_kw={
        'placeholder': 'Current Password'
    })
    new_password = PasswordField(render_kw={
        'placeholder': 'New Password'
    })
    save = SubmitField(label='Save Changes')


class ScheduleOrder(FlaskForm):
    payment_option = SelectField(label='Payment Option', choices=[
        'Cash On Delivery', 'Online'
    ])
    pickup_date = DateField(label='Pickup Date', render_kw={
        'required': 'required'
    })
    pickup_addr = StringField(label='Pickup Address', render_kw={
        'placeholder': 'Leave blank to use default address set in profile'
    })
    delivery_addr = StringField(label='Delivery Address', render_kw={
        'placeholder': 'Leave blank to use default address set in profile'
    })
    special_instr = TextAreaField(label='Special Instructions')
    clothes_count = IntegerField(label='Clothes Count', render_kw={
        'id': 'count',
        'placeholder': 'Number of clothes',
        'required': 'required'
    }, validators=[InputRequired()])
    confirm = SubmitField(label='Confirm Order')


class WriteReview(FlaskForm):
    subject = StringField(label='Subject', render_kw={
        'placeholder': 'Review subject',
        'required': 'required'
    })
    message = TextAreaField(label='Message', render_kw={
        'placeholder': 'Tell us about your experience...',
        'required': 'required',
        'rows': '20'
    })
    send = SubmitField(label='Send Review')

laundry/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

laundry/main/views.py
import datetime
import random

from flask import render_template, url_for, redirect, flash, session, current_app, request
from flask_login import current_user, login_required
from wtforms.validators import ValidationError
from sqlalchemy.exc import IntegrityError, DatabaseError

from laundry import db
from laundry.main import main
from laundry.models import Order, Message, User
from laundry.main.forms import EditProfile, ScheduleOrder



@main.route('/')
def home():
    return render_template('shared/home.html')


@main.route('/home')
@login_required
def user_home():
    return render_template('main/user_home.html')


@main.route('/terms', methods=['GET', 'POST'])
def terms():
    if request.method == 'POST':
        current_user.accepted_terms = True
        db.session.commit()
        return redirect(url_for('.user_home'))
    return render_template('shared/terms.html')


@main.route('/support')
@login_required
def support():
    return render_template('shared/support.html')


@main.route('/create_account', methods=['GET', 'POST'])
def create_account():
    if request.method == 'POST':
        try:
            form = request.form
            pass2 = form.get('confirm_password')
            pass1 = form.get('password')
            if pass1 != pass2:
                flash('Passwords must match', 'misc')
                return redirect(url_for('.create_account'))
            user = User(
                name=form.get('name'),
                email=form.get('email'),
                phone=form.get('phone'),
                address=form.get('address'),
                password=pass1
            )
            db.session.add(user)
            db.session.commit()
            flash('Account created successfully', 'success')
            return redirect(url_for('auth.login'))
        except IntegrityError:
            flash('Email is already taken', 'misc')
            return redirect(url_for('.create_account'))
        except:
            flash('An error has occured, please try again', 'light-error')
            return redirect(url_for('.create_account'))
    return render_template('main/create_account.html')


@main.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = EditProfile(obj=current_user)
    if form.is_submitted():
        try:
            current_user.name = form.name.data
            current_user.email = form.email.data
            current_user.address = form.address.data
            current_user.phone = form.phone.data
            # Change password logic
            if form.current_password.data and form.new_password.data:
                if not current_user.verify_password(form.current_password.data):
                    flash('Incorrect current password', 'error')
                    return redirect(url_for('.profile'))
                else:
                    current_user.password = form.new_password.data
            db.session.commit()
            flash('Changes saved', 'success')
        except ValidationError:
            flash('Invalid inputs', 'misc')
            return redirect(url_for('.profile'))
        except IntegrityError:
            if current_user.email != form.email.data:
                flash('Email already taken', 'misc')
                return redirect(url_for('.profile'))
            else:
                pass
        except:
            flash('An error has occured, please try again', 'error')
            return redirect(url_for('.profile'))
        return redirect(url_for('.profile'))
    return render_template('main/profile.html', form=form)


@main.route('/orders')
@login_required
def orders():
    orders = Order.query.filter_by(user_id = current_user.id).order_by(Order.created.desc()).all()
    return render_template('main/orders.html', orders=orders)


@main.route('/write_review/<int:id>', methods=['GET', 'POST'])
@login_required
def write_review(id: int):
    order = Order.query.get(id)
    orders = current_user.orders
    if order not in orders:
        return redirect(url_for('main.profile'))
    
    if request.method == 'POST':
        if 'subject' in request.form and 'message' in request.form:
            message = Message(
                subject=request.form.get('subject'),
                message=request.form.get('message'),
                user_id=current_user.id,
                order_id=id
            )
            # mark order as reviewed
            order.reviewed = True
            db.session.add(message)
            db.session.commit()
            flash('Review sent', 'success')
            return redirect(url_for('.orders'))
        else:
            # print("Subject or message not found in request.form")  # Debug statement
            flash('Please enter a review subject and message')
            return redirect(url_for('.write_review'))

    return render_template('main/write_review.html', id=id)


def create_order(data: dict) -> Order:
    """Helper function for creating an order after scheduling and/or making the payment
    
    Keyword arguments:
    data -- Order form data
    Return: None
    """

    order = Order(**data)
    db.session.add(order)
    db.session.commit()
    return order


def random_delivery_date(pickup_date):
    number = random.randint(3, 7)
    return pickup_date + datetime.timedelta(days=number)


@main.route('/schedule', methods=['GET', 'POST'])
@login_required
def schedule():
    form = ScheduleOrder()
    services = {
        'WASH & IRON': 200, 
        'WASH': 100, 
        'IRON': 100, 
        'STEAM': 150, 
        'BLEACH': 200, 
        'STAIN REMOVAL': 300
    }
    if form.validate_on_submit():
        try:
            service = request.form.get('service')
            clothes_count = form.clothes_count.data
            service_cost = services.get(service)
            amount = service_cost * form.clothes_count.data
            pickup_date = datetime.datetime.strptime(str(form.pickup_date.data), '%Y-%m-%d')
            delivery_date = random_delivery_date(pickup_date)
            # store form data for processing
            session.setdefault('order_data', {
                'amount': amount,
                'special_instr': form.special_instr.data,
                'service_type': service,
                'clothes_count': clothes_count,
                'pickup_date': pickup_date,
                'delivery_date': delivery_date,
                'pickup_addr': form.pickup_addr.data or current_user.address,
                'delivery_addr': form.delivery_addr.data or current_user.address,
                'user_id': current_user.id
            })
            if form.payment_option.data == 'Online':
                return redirect(url_for('.pay_paystack'))
            else:
                return redirect(url_for('.place_order'))
        except ValidationError:
            flash('Invalid inputs', 'misc')
            return redirect(url_for('.schedule'))
        except:
            flash('An error has occured, please try again', 'error')
            return redirect(url_for('.schedule'))
    return render_template('main/schedule.html', form=form, services=services)


@main.route('/schedule/<int:id>')
@login_required
def order_success(id):
    order = Order.query.get(id)
    return render_template('main/success_order.html', order=order)


@main.route('/pay_paystack', methods=['GET', 'POST'])
@login_required
def pay_paystack():
    order_data = session.get('order_data')
    cost = order_data.get('amount')
    transaction = current_app.config.get('API_OBJECT')
    # initialize transaction
    response = transaction.initialize(
        email = current_user.email,
        amount = cost * 100,
        label = current_user.name,
        callback_url = url_for(endpoint='.place_order', _external=True)
    )
    session['reference'] = response.get('reference')
    return redirect(response.get('authorization_url'))


@main.route('/place_order')
@login_required
def place_order():
    try:
        order = create_order(session.pop('order_data'))
    except IntegrityError:
        flash('Please fill the address fields', 'misc')
        return redirect(url_for('.schedule'))
    except DatabaseError:
        flash('A database error has occured, please try again.', 'error')
        return redirect(url_for('.schedule'))
    except:
        flash('An error has occured, please try again', 'error')
        return redirect(url_for('.schedule'))
    return redirect(url_for('.order_success', id=order.id))

laundry/templates/main/create_account.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="image/png" sizes="99x97" rel="icon" href="/static/img/icon.png">

    <!-- PURE.CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/base-min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/grids-responsive-min.css">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/pure-custom.css') }}", type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/my_custom.css') }}", type="text/css">

    <title>Shining Suds - Create Account</title>
</head>

<body style="background-color: #072D60;">
    <!-- Main Content -->
    <div class="login">
        <div class="center">
            <a href="{{ url_for('main.home') }}"><img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white"></a>
        </div>
        <div class="center-text">
            <h1>Create Account</h1>
        </div>

        <div class="content">
            <form method="post" class="pure-form pure-form-stacked">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <div class="center" class="mg-zero">
                    <label for="name">
                        Name
                        <input required type="text" name="name">
                    </label>
                </div>
                <div class="center" class="mg-zero">
                    <label for="email">
                        E-mail
                        <input required type="email" name="email">
                    </label>
                </div>
                <div class="center" class="mg-zero">
                    <label for="phone">
                        Phone Number
                        <input required type="tel" name="phone">
                    </label>
                </div>
                <div class="center" class="mg-zero">
                    <label for="address">
                        Address
                        <input required type="text" name="address">
                    </label>
                </div>
                <div class="center" class="mg-zero">
                    <label for="email">
                        Password
                        <input required type="password" name="password">
                    </label>
                </div>
                <div class="center" class="mg-zero">
                    <label for="confirm_password">
                        Confirm Password
                        <input required type="password" name="confirm_password">
                    </label>
                </div>
                <!-- FLASH MESSAGES -->
                {% for category, msg in get_flashed_messages(with_categories=True) %}
                <div class="center-text">
                    <span class="{{ category }}">{{ msg }}</span>
                </div>
                {% endfor %}
                <div class="center mg-top-20">
                    <input type="submit" value="SIGN UP" class="pure-button pure-button-primary boring-btn">
                </div>
            </form>

            <a href="{{ url_for('auth.login') }}" class="center mg-top-20">Already have an account? Login here</a>
        </div>
    </div>

    <script src="{{url_for('static', filename='js/main.js') }}"></script>
    <script src="{{url_for('static', filename='js/ui.js') }}"></script>
</body>

</html>

laundry/templates/main/orders.html
{% extends "shared/base.html" %}

{% block title %}My Orders{% endblock %}

{% block content %}

<div id="main" style="min-height: 100vh;">
    <!-- FLASH MESSAGES -->
    {% for category, msg in get_flashed_messages(with_categories=True) %}
    <div class="pop-flash">
        <span class="{{ category }}">{{ msg }}</span>
    </div>
    {% endfor %}

    <div class="header custom-header">
        <h2>My Orders <img src="/static/img/svg/order.svg" width="40px" alt="" class="mg-top-20"></h2>
        <div id="header-logo"></div>
        <img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white">
    </div>

    <div class="content" id="inProgress">
        {% if orders == [] %}
        <h1 class="center">No orders yet</h1>
        {% else %}
        <div class="pure-g">
            <div class="pure-u-1-2">
                <button type="button" class="tab-button active" onclick="orderView('current')">Current Orders</button>
            </div>
            <div class="pure-u-1-2">
                <button type="button" class="tab-button" onclick="orderView('past')">Past Orders</button>
            </div>
        </div>

        <hr style="margin: 0;">

        <div class="pure-g" id="current">
            {% for order in orders %}
            {% if not order.status %}
            <div class="pure-u-1 order">
                <h1>Order #{{ '{:04d}'.format(order.id) }}</h1>
                <p>Pickup: {{ order.pickup_date.strftime('%a, %d %b %Y') }} at {{ order.pickup_addr }}</p>
                <p>Delivery: {{ order.delivery_date.strftime('%a, %d %b %Y') }} at {{ order.delivery_addr }}</p>
                <p>Service Type: {{ order.service_type }}</p>
                <h4>Cost: {{ '₦{:,}'.format(order.amount) }}</h4>
                <h3>STATUS: IN PROGRESS</h3>
            </div>
            {% endif %}
            {% endfor %}
        </div>

        <div class="pure-g" id="past" style="display: none;">
            {% for order in orders %}
            {% if order.status %}
            <div class="pure-u-1 order">
                <h1>Order #{{ '{:04d}'.format(order.id) }}</h1>
                <p>Pickup: {{ order.pickup_date.strftime('%a, %d %b %Y') }} at {{ order.pickup_addr }}</p>
                <p>Delivery: {{ order.delivery_date.strftime('%a, %d %b %Y') }} at {{ order.delivery_addr }}</p>
                <p>Service Type: {{ order.service_type }}</p>
                <h4>Cost: {{ '₦{:,}'.format(order.amount) }}</h4>
                <h3>STATUS: COMPLETED</h3>
                {% if not order.reviewed %}
                <a href="{{ url_for('.write_review', id=order.id) }}" class="pure-button pure-button-primary boring-btn">Write Review</a>
                {% else %}
                <input type="button" value="Review Written" class="pure-button pure-button-primary boring-btn" disabled>
                {% endif %}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

laundry/templates/main/profile.html
{% extends "shared/base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}

<div id="main">
    <!-- FLASH MESSAGES -->
    {% for category, msg in get_flashed_messages(with_categories=True) %}
    <div class="pop-flash">
        <span class="{{ category }}">{{ msg }}</span>
    </div>
    {% endfor %}

    <div class="header custom-header">
        <h2>Profile <img src="/static/img/svg/profile.svg" width="40px" alt="" class="mg-top-20"></h2>
        <img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white">
    </div>

    <div class="content">
        <form method="POST" class="pure-form pure-form-stacked" autocomplete="off">
            {{ form.hidden_tag() }}

            <fieldset>
                <legend>MY PROFILE</legend>
                <div class="pure-g">
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.name.label }}
                        {{ form.name(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.email.label }}
                        {{ form.email(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.phone.label }}
                        {{ form.phone(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1">
                        {{ form.address.label }}
                        {{ form.address(class='pure-u-23-24') }}
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>ACCOUNT SETTINGS</legend>
                <div class="pure-g">
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.current_password.label }}
                        {{ form.current_password(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.new_password.label }}
                        {{ form.new_password(class='pure-u-23-24') }}
                    </div>
                </div>
            </fieldset>

            <div class="pure-u-1 center">
                {{ form.save(class='pure-button pure-button-primary boring-btn') }}
            </div>
            
            <fieldset class="center">
                <legend class="center-text">HELP CENTER</legend>
                <div class="pure-g">
                    <!-- <div class="pure-u-1 pure-u-md-1-3">
                        <a href="#" class="mg-round pure-button pure-button-primary general">Support</a>
                    </div> -->
                    <div class="pure-u-1 pure-u-md-1-3">
                        <a href="{{ url_for('main.terms') }}" class="mg-round pure-button pure-button-primary general">Terms &amp; Conditions</a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

</div>

{% endblock %}

laundry/templates/main/schedule.html
{% extends "shared/base.html" %}

{% block title %}Schedule{% endblock %}

{% block content %}

<div id="main">
    <!-- FLASH MESSAGES -->
    {% for category, msg in get_flashed_messages(with_categories=True) %}
    <div class="pop-flash">
        <span class="{{ category }}">{{ msg }}</span>
    </div>
    {% endfor %}

    <div class="header custom-header">
        <h2>Schedule <img src="/static/img/svg/schedule.svg" width="40px" alt="" class="mg-top-20"></h2>
        <img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white">
    </div>

    <div class="content">
        <form method="POST" class="pure-form pure-form-stacked">
            {{ form.hidden_tag() }}

            <fieldset>
                <legend>SERVICE</legend>
                <div class="pure-g">
                    <div class="pure-u-1 pure-u-md-1-3">
                        <label for="service">Select Service:</label>
                        <select id="service" name="service" onchange="calculateTotal()" class="pure-u-23-24">
                            {% for service, price in services.items() %}
                                <option value="{{ service }}" data-price="{{ price }}">{{ service }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.clothes_count.label }}
                        {{ form.clothes_count(class='pure-u-23-24', oninput="calculateTotal()") }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.pickup_date.label }}
                        {{ form.pickup_date(class='pure-u-23-24', id='pickup_date') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-2">
                        {{ form.pickup_addr.label }}
                        {{ form.pickup_addr(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-2">
                        {{ form.delivery_addr.label }}
                        {{ form.delivery_addr(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1">
                        {{ form.special_instr.label }}
                        {{ form.special_instr(class='pure-u-1') }}
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>PAYMENT</legend>
                <div class="pure-g">
                    <div class="pure-u-1 pure-u-md-1-3">
                        {{ form.payment_option.label }}
                        {{ form.payment_option(class='pure-u-23-24') }}
                    </div>
                    <div class="pure-u-1 pure-u-md-1-3">
                        <label for="cost">Total Cost:</label>
                        <p>₦ <span id="totalPrice">0</span></p>
                        <!-- <input type="text" name="totalPrice" id="totalPrice" value="₦ 0" readonly> -->
                    </div>
                </div>
            </fieldset>

            <div class="pure-u-1 center">
                {{ form.confirm(class='pure-button pure-button-primary boring-btn') }}
            </div>
        </form>
    </div>

</div>

{% endblock %}

laundry/templates/main/success_order.html
{% extends "shared/base.html" %}

{% block title %}Schedule{% endblock %}

{% block content %}

<div id="main">
    <!-- FLASH MESSAGES -->
    {% for category, msg in get_flashed_messages(with_categories=True) %}
    <div class="pop-flash">
        <span class="{{ category }}">{{ msg }}</span>
    </div>
    {% endfor %}

    <div class="header custom-header">
        <h2>Schedule <img src="/static/img/svg/schedule.svg" width="40px" alt="" class="mg-top-20"></h2>
        <img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white">
    </div>

    <div class="content">
        <h1>Dear {{ current_user.name }},</h1>
        <div class="center-text">
            <img src="{{ url_for('static', filename='img/svg/success-svgrepo-com.svg') }}" alt="success-icon"> <br>
            <h3>Your pickup for {{ order.pickup_date.strftime('%a, %d %b %Y') }} has been scheduled. You will be contacted a few hours prior to the pickup.</h3>
            <h3>
                Estimated delivery date: {{ order.delivery_date.strftime('%a, %d %b %Y') }}
            </h3> 
            <br>
            <h3>Pickup location: {{ order.pickup_addr }}</h3>
            <h3>Delivery location: {{ order.delivery_addr }}</h3>

            <h3>Cost: {{ '₦{:,}'.format(order.amount) }}</h3>

            <a href="{{ url_for('.orders') }}" class="pure-button pure-button-primary boring-btn">OKAY</a>
            <br> <br>
            <a href="#">Need to reschedule? Contact Support.</a>
        </div>
    </div>

</div>

{% endblock %}

laundry/templates/main/user_home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="image/png" sizes="99x97" rel="icon" href="/static/img/icon.png">

    <!-- PURE.CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/base-min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/grids-responsive-min.css">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/pure-custom.css') }}", type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/my_custom.css') }}", type="text/css">

    <title>Shining Suds - Home</title>
</head>

<body>
  <!-- FLASH MESSAGES -->
  {% for category, msg in get_flashed_messages(with_categories=True) %}
  <div class="pop-flash">
      <span class="{{ category }}">{{ msg }}</span>
  </div>
  {% endfor %}

  <div class="header custom-header">
    <h1>Home</h1>
    <img src="{{ url_for('static', filename='img/svg/icon-title-white.svg') }}" alt="icon-title-white">
  </div>

  <div class="user-content">
    <!-- welcome message with schedule button -->
    <div class="welcome">
      <h1>Welcome to <br> Shining Suds <br> Laundromat</h1>
      <a href="{{ url_for('main.schedule') }}" class="pure-button pure-button-primary general home-button">SCHEDULE NOW</a>
    </div>

    <h2>How It Works</h2>

    <!-- how it works section -->
    <div class="row-list">
      <div>
        <img src="{{ url_for('static', filename='img/svg/schedule-calendar.svg') }}" alt="schedule-icon"width="70px">
        We Collect
      </div>
      <div>
        <img src="{{ url_for('static', filename='img/svg/bubbles.svg') }}" alt="schedule-icon"width="70px">
        We Clean
      </div>
      <div>
        <img src="{{ url_for('static', filename='img/svg/truck.svg') }}" alt="schedule-icon"width="70px">
        We Deliver
      </div>
    </div>

    <!-- fast, reliable, seamless -->
    <div class="mg-bot-50 hype" style="height: 200px;">
      <h2>FAST•RELIABLE•SEAMLESS</h2>
    </div>
  </div>

  <!-- footer -->
  <div class="footer">
    <h2 class="footer-header">Contact Us:</h2>
    <div class="footer-row">
      <div>
        <img src="{{ url_for('static', filename='img/svg/phone.svg') }}" alt="phone-icon"width="30px">
        <a href="tel:+2347043859619">07043859619</a>
      </div>
      <div>
        <img src="{{ url_for('static', filename='img/svg/mail.svg') }}" alt="mail-icon"width="30px">
        <a href="mailto:shiningsuds@gmail.com">shiningsuds@gmail.com</a>
      </div>
      <div>
        <img src="{{ url_for('static', filename='img/svg/location.svg') }}" alt="location-icon"width="30px">
        No. 1, Brains and Hammers Estate, <br> Galadimawa, Abuja
      </div>
    </div>
  </div>

  <script src="{{url_for('static', filename='js/main.js') }}"></script>
  <script src="{{url_for('static', filename='js/ui.js') }}"></script>
</body>

</html>

laundry/templates/main/write_review.html
{% extends "shared/base.html" %}

{% block title %}Review Order{% endblock %}

{% block content %}

<div id="main">
    <!-- FLASH MESSAGES -->
    {% for category, msg in get_flashed_messages(with_categories=True) %}
    <div class="pop-flash">
        <span class="{{ category }}">{{ msg }}</span>
    </div>
    {% endfor %}

    <div class="header">
        <h1>Review Order</h1>
        <h2>Write a review for order #{{ '{:03d}'.format(id) }}</h2>
    </div>
    
    <div class="content mg-top-20">
        <form method="post" class="pure-form pure-form-stacked">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
            <div class="pure-g">
                <div class="pure-u-1 center">
                    <label for="subject">
                        Subject
                        <input type="text" name="subject" required placeholder="Review Subject" id="subject">
                    </label>
                </div>
                <div class="pure-u-1 center">
                    <label for="message">
                        Message
                        <textarea name="message" placeholder="Tell us about your experience..." id="message" cols="30" rows="5"></textarea>
                    </label>
                </div>
            </div>
            
            <div class="center mg-top-20">
                <input type="submit" value="Send Review" class="boring-btn pure-button pure-button-primary">
            </div>
        </form>
    </div>
</div>

{% endblock %}